### ISSUE TITLE
No Buttons in Confirm-Dialog with Bootstrap 3.4.1

### ISSUE THREAD

**Issue by jheider** [mistic100/Bootstrap-Confirmation#100]
Since Bootstrap 3.4.1 the buttons are not rendered in confirm-Dialog, 3.4.0 was working fine. Tested version is Bootstrap Confirmation 2.4.1.

**Comment by BigOHenry** [comment]
Confirmed. Same problem here.

**Comment by mistic100** [comment]
Released 2.4.3 and 4.0.3
