### ISSUE TITLE
A confirmation with 'popout' true and trigger 'manual' doesn't work as expected.

### ISSUE THREAD

**Issue by vsajip** [mistic100/Bootstrap-Confirmation#101]
I am having a problem when I initialize a confirmation with `popout` set to true and with `trigger` set to `manual`. The confirmation appears as expected the first time, but if closed without confirmation, then it doesn't seem to appear again. Getting the debugger out and setting breakpoints, I find that the confirmation _is_ shown again, but then is hidden again almost immediately afterwards by this code, which is triggered on the shown event:
```
    // close all popover already initialized
    $(self.options._selector).filter(function() {
      return $(this).data('bs.confirmation') !== undefined;
    }).confirmation('hide');
```
There is a check just above this which is supposed to prevent this:
```
    if ($(self.config._selector).is(e.target)) {
      return;
    }
```
However, it fails because my setup is like this:
```
<a id="logout" href="#" data-original-title="" title=""><i class="fa fa-sign-out" title="Sign out"></i></a>
```
I attach the confirmation to `#logout`, but `e.target` is the `<i>` element, so the check fails to return. I think the check perhaps shouldn't be for `is(e.target)` but instead a check for it containing `e.target`.

Here is a fiddle showing the problem: https://jsfiddle.net/vsajip/j24zwtdq/

**Comment by mistic100** [comment]
The problem is because you set `eventConfirmation` to `click`, ending in a loop with your own event listener.

Either :
- set `eventConfirmation` to something else
- use the `confirmed.bs.confirmation` event
- use the the flag Confirmation passes to the event listener (not recommended, subject to change) :

```js
$('#logout').on('click', function(e, ack) {
  if (ack) {
    /* clicked from Confirmation */
  }
  else {
   /* direct click */
   check_logout(e);
  }
});
```

**Comment by vsajip** [comment]
None of the approaches you suggest seem to work - could you clarify?

> * set eventConfirmation to something else
> * use the confirmed.bs.confirmation event

I set `eventConfirmation` to `'confirmed.bs.confirmation'` and added
```
$('#logout').on('confirmed.bs.confirmation', do_logout);
```
It still doesn't work - see https://jsfiddle.net/vsajip/9f1k8g62/.

> * use the onConfirm callback

Note that the original fiddle and the above fiddle both specify `onConfirm: do_logout` already.

> * use the the flag Confirmation passes to the event listener (not recommended, subject to change)

I changed the code in the original fiddle to

```
  $('#logout').on('click', function(e, conf) {
    if (conf) {
      // clicked from confirmation
      do_logout();
    }
    else {
      check_logout();
    }
  });
```

See https://jsfiddle.net/vsajip/t3ysfueo/ - it doesn't even bring up the confirmation once.

Perhaps I've misunderstood what you're getting at - I'd be grateful for some additional clarification.

Notice that I established by debugging that the confirmation _is_ shown the second time - it's just hidden immediately again because of the failing check when `popout` is `true`.

**Comment by mistic100** [comment]
Resolved an published.

BTW `confirmed.bs.confirmation` is the default event, no need to define it

**Comment by vsajip** [comment]
Great, thanks for the quick turnaround!
