### ISSUE TITLE
data-confirmation-event on anchor tag not working as expected

### ISSUE THREAD

**Issue by JamesPoel** [mistic100/Bootstrap-Confirmation#102]
Hi,

If `data-confirmation-event` it set on an anchor tag, the browser is still redirected after the custom event runs.

Example:

```
<script>
$('.test').confirmation().on('custom-event',function(e){ alert('Hello World!'); e.preventDefault(); });
</script>

<a href="/hello" class="test" data-toggle="confirmation" data-confirmation-event="custom-event">Run Test</a>
```

Clicking *Run Test* alerts "Hello World!", and then redirects to the url /hello.
I think the expected behaviour would be to alert "Hello World!" without redirecting the browser?

**Comment by JamesPoel** [comment]
I have found a fix for this issue; this is the line causing the issue:
https://github.com/mistic100/Bootstrap-Confirmation/blob/fe30ffd1f5d8b4a61d4bd89d96a2cdea540de010/src/confirmation.js#L340

If this is changed to `if ($(this).attr('href') === '#' || self.config.confirmationEvent !== 'click') {`, the problem is resolved.

**Comment by mistic100** [comment]
I thought about it and I don't agree. If you don't want a redirect when the confirmation is validated, then just don't put an `href` on the link.
You can also change the `copyAttributes` option to prevent `href` from being copied to the validate button.
