### ISSUE TITLE
stopImmediatePropagation on click confirm not working

### ISSUE THREAD

**Issue by alicankablan** [mistic100/Bootstrap-Confirmation#107]
I am trying stop the postback on my asp.net project if stopEvent true. But it doesnt stop it is continue on event. For understanding my goal is need cancel the confirm click or dispose or quit.

```js
var item = $('[data-toggle=confirmation]');
        item.on('confirmed.bs.confirmation', function(e,v) { 
           if(stopEvent){
               e.stopImmediatePropagation();
            //e.preventDefault();
           }
        });
        item.confirmation({ btnOkLabel: 'Yes', btnCancelLabel: 'No', title: 'Are you sure?' });
```
```html
        <a id="cphBody_grdPopulasyon_lnkOnayla_0" class="btn btn-success btn-xs" data- 
         toggle="confirmation" 
         href="javascript:__doPostBack('ctl00$cphBody$grdPopulasyon$ctl02$lnkOnayla','')" 
         style="cursor: pointer" data-original-title="" title="" aria- 
        describedby="confirmation108897"><i class="fa fa-check"></i></a>
  ```

**Comment by mistic100** [comment]
and if you uncomment "preventDefault" ?  
Because here your need to preventDefault, immediatePropagation only concerns events handler, why you are trying to stop is not an event handler, it's is the "href" of your link which is the "default" behavior.

**Comment by alicankablan** [comment]
I try preventDefault it is not working I can give any information about the problem for fixing how can I help you.

**Comment by mistic100** [comment]
What exactly are you trying to do ?
Unfortunately your sentence "my goal is need cancel the confirm click or dispose or quit" makes no sense.

**Comment by alicankablan** [comment]
You have right my english is bad I am sorry. I am trying stop the postback (refreshing the page). On confirm click I check something. If everything is not okey the confirm event must be stop and postback too.

**Comment by mistic100** [comment]
preventDefault is definitely the solution. I cannot tell why it wouldn't work, I never used asp.net
