### ISSUE TITLE
Popout option does not work with Bootstrap  v3.3.2

### ISSUE THREAD

**Issue by shuxer** [mistic100/Bootstrap-Confirmation#11]
Hi :),

Thanks for this great plugin. I seems there is a bug with popout option when the plugin is used with the latest Bootstrap  v3.3.2. I hope you can take a look at this issue. 

Thanks.

**Comment by shuxer** [comment]
Hi,

Actually it was't the latest bootstrap v3.3.2 issue. It has something to do with the initialization method:

Below global initialization works fine when data-popout="true" passes for each individual element:
<code>
    var handleBootstrapConfirmation = function() {
        if (!$().confirmation) {
            return;
        }
        $('[data-toggle=confirmation]').confirmation({ container: 'body', btnOkClass: 'btn-xs btn-success', btnCancelClass: 'btn-xs btn-danger'});
    }
</code>

But when using below individual initialization data-popout="true" does not work:

<code>
    var handleBootstrapConfirmation = function() {
        if (!$().confirmation) {
            return;
        }
        $('[data-toggle=confirmation]').each(function() {
            $(this).confirmation({ 
                container: 'body', 
                btnOkClass: $(this).attr('data-btn-ok-class') ? $(this).attr('data-btn-ok-class') : 'btn-xs btn-success', 
                btnCancelClass: $(this).attr('data-btn-cancel-class')? $(this).attr('data-btn-cancel-class') : 'btn-xs btn-danger'
            });
        });
    }
</code>

Thanks.

**Comment by mistic100** [comment]
I don't think it has anything to do with the version of bootstrap.

initializing a plugin in a each() is generally bad practice, you should ensure all your items have the necessary data attributes and use global initialization

now why it does work ? (just guesses, I didn't test)
the popout & delegate features where two things very difficult to get working together, my solution was to keep trace of all items initialized together, thus don't work with your each

**Comment by mistic100** [comment]
Another solution for your case is to overwrite Confirmation defaults

```js
$.extend($.fn.confirmation.Constructor.DEFAULTS, {
    btnOkClass: 'btn-xs btn-success', 
    btnCancelClass: 'btn-xs btn-danger'
});
```
