### ISSUE TITLE
Irritating scrolling of page to top after "onConfirm" from popup

### ISSUE THREAD

**Issue by kikonen** [mistic100/Bootstrap-Confirmation#121]
Just noticed rather irritating behaviour. For some reason after "onConfirm" is handled, apparently this confirm widget is somehow triggering "scroll page to top". Naturally behaviour is very irritating for user if confirm popup is shown in the end of long page. Issue does not occur if popup confirm is canceled, however.

After disabling this confirm widget this undesired "scroll to top" disappeared.

Still debugging what causes this strange scrolling, but so far it seems that it's happening somewhere in "bootstrap-confirmation" or "popper.js".

**Comment by mistic100** [comment]
Are your sure you don't have a `href="#"` on the link you apply the widget to ?  
Because this behavior is not present on the demo http://bootstrap-confirmation.js.org/

Otherwise please provide an online example of the problem.

**Comment by kikonen** [comment]
Yesh!, "href="#" likely explains it.

bootstrap-confirmation.js#428 seems to be source for it
````

    _proto._setButtons = function _setButtons($tip, buttons) {
      var self = this;
      var $group = $tip.find(Selector.BUTTONS).empty();
      buttons.forEach(function (button) {
        var btn = $('<a href="#"></a>').addClass(BTN_CLASS_BASE).addClass(button.class || BTN_CLASS_DEFAULT + " btn-second
```

**Comment by mistic100** [comment]
There is also https://github.com/mistic100/Bootstrap-Confirmation/blob/master/src/confirmation.js#L366-L368  
so I don't really know what could be the problem

**Comment by kikonen** [comment]
yes, a bit unclear what is happening; I try to debug more to track what's going on (hopefully time soonish for that). Based into code, I would have assumed that it should work, and not trigger "#" link following.

hmm... that made some recallings to me, recalling that I was hitting some trouble with jquery and trying to prevent default at some point  of time.

aka. https://stackoverflow.com/questions/27870794/jquery-click-event-preventdefault-not-working

Q: Is there need to explicitly "return false;" in addition to preventDefault()?
