### ISSUE TITLE
Confirmation and title

### ISSUE THREAD

**Issue by solomax** [mistic100/Bootstrap-Confirmation#125]
Not sure if this is issue or I want too much :)

I have button with title attribute set
```
<button class="btn btn-primary" title="Delete user record" id="A">Delete</button>
```
I'm setting confirmation with custom title:
```
$('#A').confirmation({
  "btnCancelLabel":"Cancel"
  ,"btnOkLabel":"OK"
  ,"title":"Do you really want to delete this item?"
  ,"btnOkClass":"btn btn-sm btn-danger"
  ,"btnOkIconClass":"fas fa-exclamation-triangle"
  ,"rootSelector":"A"});
```
then displaying it:
```
$('#A').confirmation('show');
```

As a result I'm getting confirmation with title: `Delete user record` NOT `Do you really want to delete this item?`

Is it possible to have configured title for confirmation and unchanged title for button?

confirmation version 4.1.0

**Comment by mistic100** [comment]
Hello

this is how BT Popover behaves, I have no intention to change it.

FYI this is the part of BT which removes the original title when Tooltip or Popover is applied to an element https://github.com/twbs/bootstrap/blob/master/js/src/tooltip.js#L584

**Comment by mistic100** [comment]
On second though you could probably define your element with "title" AND "data-original-title" in order to keep the title and have a separated one of the confirmation.

But this is not documented by BT

**Comment by solomax** [comment]
Actually I tried to define `data-original-title` but this have no effect
if title exists it will dropped and moved to `data-original-title` and no luck :((
Maybe you can add option to declare `config.title` has more priority than `title`?

**Comment by mistic100** [comment]
Confirmation relies on default implementation of getTitle() form Bootstrap. I don't want to owerride it.

**Comment by solomax** [comment]
I always thought of `title` as of something being displayed on `hover` (describing current element)
Confirmation is actually something acting on-click, 

will try to find something that can do the job for me
Thanks for your time
