### ISSUE TITLE
Usage Comment

### ISSUE THREAD

**Issue by DifTechDesigns** [mistic100/Bootstrap-Confirmation#130]
Not an issue, just a comment but I didn't find anywhere else to leave one.

If you're creating your buttons dynamically, you will need to put the following code below the line where you're dynamically inserting your buttons.
`$('[data-toggle=confirmation]').confirmation({
  rootSelector: '[data-toggle=confirmation]',
 
});` 

Example: 
`function addButton(str){
     let btn = "<button  value=str>Click</button>;
     $("#some_div").html(btn);
     $('[data-toggle=confirmation]').confirmation({
    rootSelector: '[data-toggle=confirmation]', 
});
}`

If you're creating multiple buttons at once,  you only need to add it at the end after all the buttons are written.

`$.each(results, function(key, item){
    //create buttons

});
$('[data-toggle=confirmation]').confirmation({
    rootSelector: '[data-toggle=confirmation]', 
`

**Comment by mistic100** [comment]
Or you can use the "selector" option as explained in Bootstrap documentation (link on the top of the "Options" section)

```js
$('.some-container').confirmation({
   rootSelector: '.some-container',
   selector: '[data-toggle=confirmation]',
});
```

Unfortunately I cannot copy every inherited Bootstrap option.

**Comment by DifTechDesigns** [comment]
Ah, thank you. I didn't see that. Very helpful. BTW - You plugin was the perfect solution for what I needed for one of my clients.
