### ISSUE TITLE
Buttons over data-* attribs

### ISSUE THREAD

**Issue by landy2005** [mistic100/Bootstrap-Confirmation#135]
Please make Button params configurable over data-* attribs.

I.e.:
- btnOkLabel - data-ok-label
- btnOkClass - data-ok-class
- btnOkIcon - data-ok-icon
- btnOkIconClass - data-ok-icon-class

**Comment by mistic100** [comment]
This is already possible and **it is written in the documentation**

If it does not work for you, create an online demo.

**Comment by landy2005** [comment]
seems as not work (or unavailable) for 2.x.

**Comment by mistic100** [comment]
Works fine https://jsfiddle.net/mistic100/u0dwm2vb/2/

**Comment by landy2005** [comment]
sorry, I found correct data attrib names.
(in documentation not clearly written which data attrib names).

Attrib named "btnOkClass" but data attrib named "data-btn-ok-class".
I tried "data-btnOkClass"..

**Comment by mistic100** [comment]
From the documentation

> Options can be passed via data attributes or JavaScript plain object. For data attributes, append the option name to data-, as in data-btn-ok-class="".

I don't know how it can be more clear.

And it's the same for BT 3 official doc https://getbootstrap.com/docs/3.3/javascript/#popovers-usage

**Comment by landy2005** [comment]
As I can see not clear ;)

BS3 docs, option Name "placement" -> attrib name "data-placement",
Your docs, option Name "btnOkClass" -> attrib name "data-btn-ok-class"..
where written that camelCase name should be converted to lowercase with dashes.

**Comment by mistic100** [comment]
This is not specific to Bootstrap not Confirmation but is common JS API 
ere https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by landy2005** [comment]
I agree that this is common naming for attribs, but anyway your docs not clear about camelcase name conversion.
Why not "data-btnokclass" (I tried this name too).

**Comment by mistic100** [comment]
I don't make the naming conventions : camelCase => dash-case , that's is, it's not even decided by BS, this is how the data API works.

And I also consider the sentence `as in data-btn-ok-class=""` in my doc is plenty enough to understand what is going on.

I nothing more to say.
