### ISSUE TITLE
Can you add a license to the project?

### ISSUE THREAD

**Issue by Gira-X** [mistic100/Bootstrap-Confirmation#144]
Right now, this repository falls in the 'no license' category and I am not sure if I can use it for commercial work.

See https://choosealicense.com/no-permission/

**Comment by mistic100** [comment]
There is a license https://github.com/mistic100/Bootstrap-Confirmation/blob/master/package.json#L6

This is (one of) the way to declare the license on NPM packages.

**Comment by Gira-X** [comment]
Ah interesting, thanks! I was expecting a dedicated license file!
