### ISSUE TITLE
Only copy href on confirmation can change the application behaviour

### ISSUE THREAD

**Issue by Yoshyn** [mistic100/Bootstrap-Confirmation#15]
Hi.

I try to use your code with Rails in order to have confirmation when i delete my object.

With rails, to delete an object, i have a link like this : 
```html
<a rel="nofollow" data-method="delete" href="/my_model/1">Remove</a>
```
This simulate an HTTP delete request for rails.

Unfortunately, with your code, the confirm link is : 
```html
   <a href="/my_model/1" target="_self">Remove</a>
```
And this become a simple get request. The behavior is changed.

One solution will be to copy all the attributes except those used by this plugins.

What do you think about?

**Comment by mistic100** [comment]
copy everything ? that's the solution to have totally unpredictable side effects
there are a callback and an event on tooltip confirmation, you should use them

**Comment by Yoshyn** [comment]
My concern here was an unpredictable side effects due to the copy of the href only.

I really think that copy  **only** the link & data attributes that are not relative to this plugins can't cause more unpredictable side effects than take only few element of the link ( in fact only the href and the target).

In all cause, i can make it work using the callback. 
Thanks for your answer.
