### ISSUE TITLE
Host it in MAXCDN

### ISSUE THREAD

**Issue by Itiho** [mistic100/Bootstrap-Confirmation#17]
Host the JavaScript version in https://www.maxcdn.com/

**Comment by mistic100** [comment]
Do you know anything about politeness ? Like don't being imperative with people you don't know and do free work ?

And I don't see anything on MaxCDN saying anyone can host public libraries, perhaps you can tale some of your precious time to enlighten us.

**Comment by Itiho** [comment]
Sorry about that but my Inglês is bad.

MaxCDN enables faster deliver content using cache and multiple HTTP requests because it uses multiple domains.

The Bootstrap allows you download the ZIP file and insert into the application or use the address

<script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"> </ script>

**Comment by mistic100** [comment]
Still don't know where you see that.

CDN JS for example has a clear guide to submit a new library https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

I don't think MaxCDN provide such thing as a public shared repository.
