### ISSUE TITLE
if there is a click event listener associated with the button that triggers the confirmation, the click event listener is called before clicking the confirmation "yes"

### ISSUE THREAD

**Issue by ppazos** [mistic100/Bootstrap-Confirmation#173]
I have a button with a click listener, that listener submits a form.

The button has the bootstrap confirmation applied to it.

When the button is clicked, the click event is triggered right away, before confirming with the BS confirmation "yes".

The button:

`<button class="btn btn-danger" id="btn_cancel" data-toggle="confirmation" data-title="Are you sure?" data-confirmation-event="cancel-event">Cancel claim</button>`

Registering confirmation:

```
  $(function() {

    $('[data-toggle=confirmation]').confirmation({
      rootSelector: '[data-toggle=confirmation]',
      placement: 'left',
      btnOkClass: 'btn btn-primary',
      btnCancelClass: 'btn btn-default'
    });
....
```

And the click event:

```
$('#btn_cancel').on('click', function(e) {
   alert('click!');
});
```

I'm not sure what I'm doing wrong. I would expect the click event to not be fired until the confirm "yes" is clicked.

**Comment by mistic100** [comment]
Your expectation is wrong sorry, you have to listen to confirmation events. Other events listener are not relayed.
