### ISSUE TITLE
Confirmation popover doesn't appear unless it is clicked twice in bootstrap v3.3.5

### ISSUE THREAD

**Issue by shochinhwa** [mistic100/Bootstrap-Confirmation#20]
Seems to be an issue with bootstrap v3.3.5.

1. Click on button to popover confirmation. (working)
2. Click No.
3. Click on button to popover confirmation again (not working)
4. Click on button to popover confirmation second time (working)

Didn't have this issue in earlier bootstrap v3.3.4

**Comment by Stiropor** [comment]
I can confirm this, so far I cannot figure out what the problem is.

**Comment by gautamksr** [comment]
Hi, Confirmation popover is not working after click No. it required 2 clicks to show confirmation popover with bootstrap 3.3.5

**Comment by securit** [comment]
+1 here too

**Comment by Nenos-Hu** [comment]
Same here :)
Nice plugin by the way.

**Comment by wasiqaftab** [comment]
same issue for me. any update on it

**Comment by mistic100** [comment]
I'm open to any proposal.

**Comment by Kryptonit3** [comment]
Here is a repo that works without this issue

https://github.com/tavicu/bs-confirmation

**Comment by mistic100** [comment]
New release planned for this day
