### ISSUE TITLE
confirmation can not rebind after destroy it

### ISSUE THREAD

**Issue by awanabe** [mistic100/Bootstrap-Confirmation#22]
rt

**Comment by chaodongyue** [comment]
I also appeared this problem,how to fix it?

**Comment by mistic100** [comment]
Provide a live demo of the bug.

**Comment by awanabe** [comment]
version: Bootstrap Confirmation 2.1.3

```
 $('#element').click(function() {
     $('#element').confirmation({
            popout: true,
            title: 'This is title',
            btnOkClass: 'popout-btn popout-ok',
            btnOkLabel: 'OK',
            btnOkIcon: '',
            btnCancelClass: 'popout-btn popout-cancel',
            btnCancelLabel: 'Cancel',
            btnCancelIcon: '',
            onConfirm: function () {
                    $(this).confirmation('destroy');
            }
      }); 
});

```
Then it can not init the confirmation
```
```

**Comment by mistic100** [comment]
Why would you do that in the first place ?
If it's because your element are dynamically added you should use delegation instead (`selector` option of Bootstrap Popover)

Anyway, I can't tell what's going on

**Comment by awanabe** [comment]
My Logic:   

When I click this element, It will change status, then new confirmation (with different operation) will bind on this element , so I had to destroy original confirmation, then bind new one.
But after destroy the original one, new one can not show...

You may 
run it to reappear this bug.

**Comment by mistic100** [comment]
Has there is obviously a conflict between the click event used to initialize the confirmation, and the click event use to open it, I won't investigate further in this.

You might try to find a cleaner way to achieve what you want.
