### ISSUE TITLE
Applies hide after hide

### ISSUE THREAD

**Issue by cornex** [mistic100/Bootstrap-Confirmation#23]
Hello! Got a problem where I init the confirmation, click on it and click the no button, if you try to click the button again after you canceled it will not work, once you try again it works, it seems to run the hide event 2 times, first one when you cancel, and once again when you try to click it again.  I provide a live demo here:

http://jsfiddle.net/611ym0bd/1/

**Comment by mistic100** [comment]
duplicate of  #20
