### ISSUE TITLE
How to pass param into callback function ?

### ISSUE THREAD

**Issue by euclid1990** [mistic100/Bootstrap-Confirmation#27]
```<i class="fa fa-trash comment-tool post-comment-delete" data-toggle="confirmation" data-popout="true" data-on-confirm="DeleteComment(123)"></i>```
I want to pass parameter 123 into function DeleteComment()
How to do it ?
Thank you !

**Comment by mistic100** [comment]
Same as #24

**Comment by euclid1990** [comment]
@mistic100 thank you
