### ISSUE TITLE
Add npm package 

### ISSUE THREAD

**Issue by gabel** [mistic100/Bootstrap-Confirmation#30]
Beside bower I'd like to see a npm version available. Could you publish it to npmjs?

It will take only those 1 step just to make it available.

`npm publish`

**Comment by mistic100** [comment]
It also requires the declaration of dependencies in package.json.
Will do it as soon as possible.

**Comment by gabel** [comment]
@mistic100 You don't need to require the upstream deps (bootstrap and co) but only the ones to run/build your module. So from my point of view the devDependencies already lookin fine and no other deps are required?

**Comment by mistic100** [comment]
So what is the point on publishing it on npm if you can't use front end build tools only using npm (not bower) ?

**Comment by gabel** [comment]
Using [webpack](https://github.com/webpack/webpack) or other build tools, `npm` is the favorite way to go, as they need the sources to run their build management the right way.

**Comment by mistic100** [comment]
Yes understood that, so I repeat my question : how could it work if Bootstrap is not in the dependencies of the package file ?

**Comment by gabel** [comment]
If you don't need bootstrap to build your script then just like other libs with upstream dependencies they can be build without these dependencies but obviously cannot be used in a frontend environment without them. But that's no problem at all (other example https://github.com/stidges/jquery-searchable/blob/master/package.json). I saw libs that required the dependencies in a strange way and made it hard to load them via CDN. So don't worry about it. If you feel really bad about it you can of course add bootstrap as dependency.

**Comment by mistic100** [comment]
https://www.npmjs.com/package/bootstrap-confirmation2

**Comment by gabel** [comment]
@mistic100 thx :+1:
