### ISSUE TITLE
jQuery 3.1.0: popout and singleton features not working

### ISSUE THREAD

**Issue by spohlenz** [mistic100/Bootstrap-Confirmation#34]
These features are not currently working in the current latest jQuery release 3.1.0 (have confirmed that they do work with my configuration with jQuery 2.2.4).

This appears to be due to `this.selector` being undefined here:
https://github.com/mistic100/Bootstrap-Confirmation/blob/master/bootstrap-confirmation.js#L289

Thank you for the plugin by the way.

**Comment by mistic100** [comment]
The migration seems painful https://api.jquery.com/selector/
I'll have to re-understand how these features work (I just remember I had a headache the first time ...) and adapt

**Comment by spohlenz** [comment]
A bare minimum fix might be to allow the root selector to be passed in as an option, defaulting to `this.selector` (for backwards compatibility), falling back to an empty string `''` if it is undefined. This would make the default singleton behaviour as one confirmation per page, which doesn't seem unreasonable to me.
