### ISSUE TITLE
onConfirm and onCancel function

### ISSUE THREAD

**Issue by kevinjuliano1020** [mistic100/Bootstrap-Confirmation#37]
Hi! I saw your plugin and it's awesome feature, but unfortunately, it is now working on my site. can you help me with this?

**Comment by mistic100** [comment]
Huh ? I would but without info I can't... (this is not a forum but an issue tracker).

So if you want my help, setup a minimal demo of the problem, I won't try to find a problem if it's hidden under layers of custom code.

**Comment by kevinjuliano1020** [comment]
I'm sorry my bad, I just wanna know how to do an onConfirm or onCancel function

`$("#event1_status").confirmation({
	onConfirm: function() {
	alert('Confirmed');
	});`

is this right?

**Comment by mistic100** [comment]
yes, but you are missing a `}` at the end

Though I recommend the usage of events :

```js
var item = $("#event1_status");
item.confirmation();
item.on('confirmed.bs.confirmation', function() { 
  alert('Confirmed'); 
});
```

**Comment by kevinjuliano1020** [comment]
works like magic! you are awesome! thanks a lot! i really appreciate it :)

**Comment by mistic100** [comment]
Because I pointed out your were missing a `}` ? Your web console could have told you too.

**Comment by kevinjuliano1020** [comment]
didn't see anything on my console I'm using google chrome, and it is kinda weird it didn't came out.

**Comment by kevinjuliano1020** [comment]
thanks again i will close the issue now! :D
