### ISSUE TITLE
Feature: Keyboard Navigation

### ISSUE THREAD

**Issue by jerchende** [mistic100/Bootstrap-Confirmation#38]
It would be a really cool feature, if you could select the button with keyboard.

Like the Datepicker: https://github.com/eternicode/bootstrap-datepicker

**Comment by mistic100** [comment]
I tried to implement it, my problem so far is that the "Enter" key closes the popover by "clicking" on the main button, so the event is not received by buttons inside the popover. Some more work to go :-)
