### ISSUE TITLE
Space between buttons disappears when click on button

### ISSUE THREAD

**Issue by raelb** [mistic100/Bootstrap-Confirmation#40]
In example\index.html

The space between buttons disappears when I click on a button:

![bootstrap-img1](https://cloud.githubusercontent.com/assets/13108198/18522578/dfb883a8-7ab0-11e6-9be1-e3bb5b6a5931.png)

**Comment by mistic100** [comment]
Not related to Confirmation, it appends with standard Bootstrap Popover.

If you want to avoid this, set `container: 'body'`

```js
$('[data-toggle=confirmation]').confirmation({
    container: 'body'
  });
```

**Comment by mistic100** [comment]
Example update with `btn-group`
