### ISSUE TITLE
Popover container:body

### ISSUE THREAD

**Issue by rajankur** [mistic100/Bootstrap-Confirmation#42]
Need to add an option, container: body so that ir can be passed to inherit the cool popover feature.

**Comment by mistic100** [comment]
I does inherit Popover and it's explicitly said in the doc http://bootstrap-confirmation.js.org/#usage

> All options from Bootstrap Popover can be used except trigger.

**Comment by mistic100** [comment]
And the examples use `container` to solve issues with siblings buttons https://github.com/mistic100/Bootstrap-Confirmation/blob/master/example/index.html#L106
