### ISSUE TITLE
template option is not working

### ISSUE THREAD

**Issue by behz4d** [mistic100/Bootstrap-Confirmation#44]
Hello,

the `template` option of bootstrap is not working to define a custom popover template for the confirmation. it loads the whole thing but the buttons don't show up if we define the template as an option in this plugin.

**Comment by mistic100** [comment]
Of course, the `template`  is used by Confirmation to add the buttons.

Use `content` if you want a custom body.

**Comment by behz4d** [comment]
content only injects something into the popover, what I want to do is to have a different styling for confirmations only and not all the other website popovers. is there anyway to achieve this?

**Comment by mistic100** [comment]
Then your template must be based on the default one 
https://github.com/mistic100/Bootstrap-Confirmation/blob/master/bootstrap-confirmation.js#L53-L65

**Comment by behz4d** [comment]
yup, I edit that and add a custom css class to it, thank man.
