### ISSUE TITLE
it does not work in mobile phone 

### ISSUE THREAD

**Issue by mosesyou** [mistic100/Bootstrap-Confirmation#45]
`$('[data-toggle=confirmation]').confirmation({
        rootSelector: '[data-toggle=confirmation]'
    });`

i just use this code , it works in my web project normal ,but does not works when this project run in mobile phone. i think it cant surppot self-adaption.
wait help.

**Comment by mistic100** [comment]
Can you elaborate "it does not work" ?

**Comment by mosesyou** [comment]
when brower bigest,bootstrap-confirmation normal
![image](https://cloud.githubusercontent.com/assets/17940149/19519018/88b82dea-963c-11e6-9ab2-2a7f573f3d7f.png)
then i use bootstrap-confirmation in datatable  
` <a class="fa fa-minus btn"  href=""  data-toggle="confirmation" data-singleton="true"></a>`
when i ajust the brower width,it cant be displayed.
![image](https://cloud.githubusercontent.com/assets/17940149/19519206/80dc00c8-963d-11e6-8282-c22a239a4e97.png)

**Comment by mistic100** [comment]
Are you sure your buttons are not dynamically added/replaced to your DOM ? In this case the plugin needs to be re-attached to the new DOM elements (or use delegation with the `selector`  option, see Bootstrap doc).

If it's not the case, create a online demo of the problem.

**Comment by mistic100** [comment]
I tested the demo on my mobile without any problem.
The only issue is the placement of "Confirmation on left" which overflows the viewport. Luckily Bootstrap Popover supports `data-placement="auto left"`
