### ISSUE TITLE
Allow to stop the default action inside confirmed.bs.confirmation

### ISSUE THREAD

**Issue by snamor** [mistic100/Bootstrap-Confirmation#46]
I would like to call an AJAX request when accepting the confirmation. For this purpose I would like to stop the propagation of the event when capturing the 'confirmed.bs.confirmation', but it seems that this is not possible.

**Comment by mistic100** [comment]
Can you show an example ?

I think you have a design problem if you need to stop any action after the confirmation.

**Comment by snamor** [comment]
Thank you for the fast response!

What I'm trying to achieve is to send an ajax request when accepting the confirmation. In my case the action is inside an <a> tag and would be something similar to that:
```
$('a.delete-relationship').on('confirmed.bs.confirmation', function (e) {
                e.preventDefault();
                $.ajax({
                    url: $(this).attr("href")
                })
                    .done(function( data ) {
                        //OK actions, show an ok message.
                    })
                    .fail(function( jqXHR ) {
                        //KO actions, show an error message.
                    })
            });
```
But I've tried to return false or "preventDefault" but none of them work. 

I'm trying to follow the code and see if I can supply a working PR so we can discuss if you want.

**Comment by mistic100** [comment]
Ok I see. As I said, you have a design problem. Don't use a.href if it's not an actual link.

Use a button for example with a data-href if you want to store the AJAX url in the DOM.

**Comment by snamor** [comment]
Thanks for the advice, will try this and see if I can make it work.
