### ISSUE TITLE
How to override default option?

### ISSUE THREAD

**Issue by stefdelec** [mistic100/Bootstrap-Confirmation#47]
How to override default option without modifying the inner code of your plugin ?

**Comment by mistic100** [comment]
Like any Bootstrap component ?. http://getbootstrap.com/javascript/#popovers

```js
$('[data-toggle=confirmation]').confirmation({
  rootSelector: '[data-toggle=confirmation]',
  // other options
btnOkClass: 'my-class
});
```

**Comment by stefdelec** [comment]
Yes, that would be custumizing. Or perhaps :

In my project, I have default option for our timepicker. But sometime, it needs to be override. Usually in jquery plugin, data-attributes override default option. In your plugin, if there is default option, data-attribute settings are not taken into account.

**Comment by mistic100** [comment]
I absolutely don't understand what you want. Confirmation works exactly like the core Popover, all config handling is done by the core of Bootstrap.

So please clearly explain your need with code or search google for the same need applied to Popover.

**Comment by mistic100** [comment]
http://stackoverflow.com/a/17589388/1207670

Is that what you want ? replace `Popover` by `Confirmation` and you are done.

**Comment by stefdelec** [comment]
Thanks. Sounds good. It is what I want. Thanks for your help and your patience.
