### ISSUE TITLE
Absolute positioning issue?

### ISSUE THREAD

**Issue by fouimette** [mistic100/Bootstrap-Confirmation#48]
When I click the button, the popup gets cut off.  I am not skilled in CSS enough to fix this.  Here is a screen shot.

![image](https://cloud.githubusercontent.com/assets/5218961/20243760/40eebd5a-a922-11e6-9e26-b8a4989ad069.png)

Here is the underlying HTML for the button.

```
                        <div class="col-sm-2 col-xs-6">
                            <a class="btn btn-primary btn-xs btn-block" href="@Url.Action("Details", "Rentals", new { id = item.Header.RentalId, hash = HashHelper.Get(item.Header.RentalId.ToString()) })">
                                Edit<span class="hidden-xs"> Listing</span>
                            </a>
                            <button class="btn btn-danger btn-xs btn-block" data-toggle="confirmation" data-singleton="true" data-id="@item.Header.RentalId"
                                    data-btn-ok-label="Yes" data-btn-ok-class="btn-success" data-btn-cancel-label="No" data-btn-cancel-class="btn-danger" data-content="Remove this listing?">Deleeete me</button>
                            <a class="btn btn-danger btn-xs btn-block" href="#" data-toggle="confirmation" data-singleton="true" data-id="@item.Header.RentalId">
                                Remove<span class="hidden-xs"> this listing</span>
                            </a>
                        </div>
```

Any thoughts?

**Comment by mistic100** [comment]
container: 'body'

**Comment by mistic100** [comment]
Der bootstrap popover doc

**Comment by fouimette** [comment]
Thank you!  The solution I used was `data-container="body"` and now it shows beautifully.  Thanks for the wonderful tool.

**Comment by seyfer** [comment]
@mistic100 for me `container: 'body'` gives wrong absolute position. js put a big number in `left` property
`<div class="popover popover-confirmation popover-confirmation--blue fade top in" id="confirmation681633" style="top: 335px; left: 1665px; display: block;">`

`left: 1665px;` :see_no_evil: 
and looks like
![screenshot from 2018-10-08 15-18-36](https://user-images.githubusercontent.com/1483925/46611321-bff02580-cb0d-11e8-98da-4863da45fb1c.png)

and if I remove `container: 'body'`
then I have an issue like in this topic - it goes under the right border and not visible. :disappointed:

**Comment by seyfer** [comment]
Solved with `viewport` property set to the table id.
