### ISSUE TITLE
any plans to update this for bootstrap 4? 

### ISSUE THREAD

**Issue by spovich** [mistic100/Bootstrap-Confirmation#51]
This is a really nice popover tool!  Just spinning up a project and wanted to start with bootstrap 4 and wondering if this is planned?  Thanks!

**Comment by mistic100** [comment]
Not planned, but it doesn't mean I won't port it.

But I think it should be in a separated repository (can be a fork of this one) in order to be able to publish both versions on bower and npm.

**Comment by spovich** [comment]
ok, cool. thanks for the info.

**Comment by mistic100** [comment]
I think again about it and actually it could be the same repository.
Just need to make it clear on the doc that Bootstrap 3 users must use `bower install bootstrap-confirmation2#2.x` instead of `bower install bootstrap-confirmation2`

**Comment by ethaizone** [comment]
As former creator I'm really happy that this project can run this long. Thank @mistic100 for maintenance this project. 👍

**Comment by 9mm** [comment]
I was also curious about v4. Is that in this project right now?

**Comment by swasher** [comment]
Hi! Thank you for great software, and +1 vote to upgrade.

**Comment by arunkaruppaiah** [comment]
Another vote for v4

**Comment by adarshmadrecha** [comment]
I am really looking forward to adding this to my project once it supports bootstrap 4 since now bootstrap 4.0 stable is released
