### ISSUE TITLE
problem with Bootstrap table

### ISSUE THREAD

**Issue by jhidalgoc** [mistic100/Bootstrap-Confirmation#53]
I use with this another plugin:

http://bootstrap-table.wenzhixin.net.cn/

But  i can't see the full dialog.
This occur when i put the dialog inside a td.

**Comment by TheNiner** [comment]
For anybody who is having a similar problem while using the "bootstrap-table" plugin, you can simply listen to the `onPostBody` Event (http://bootstrap-table.wenzhixin.net.cn/documentation/#events) provided by bootstrap-table and do something like this:

```
$('#table').on('post-body.bs.table', function (data) {
    $('[data-toggle=confirmation]').confirmation({
        rootSelector: '[data-toggle=confirmation]',
        container: 'body',
    });
});
```

This worked for me.
