### ISSUE TITLE
How to distinguish in OnConfirm event which button was pressed

### ISSUE THREAD

**Issue by kaluosi** [mistic100/Bootstrap-Confirmation#58]
If I have an array of similar buttons which trigger different actions. How can I distinguish which button was clicked and confirmed with in the same OnConfirm event.

**Comment by mistic100** [comment]
As most of the jQuery world, use `$(this)`

**Comment by mistic100** [comment]
I added a `value` parameter to the button definition that will be transmited to the callbacks and the event handlers.
