### ISSUE TITLE
required configuration for always pop

### ISSUE THREAD

**Issue by ManishJain-JKV** [mistic100/Bootstrap-Confirmation#59]
If user click on "Yes" in confirmation dialog, confirmation dialog will never popup again. But what if I required every time user click on button and confirmation dialog pop.
I think this plugin required one more configuration using which this functionality can be achieved.

**Comment by mistic100** [comment]
The behavious you are discribing is a bug, it should not happen.
Please provide a demo of the bug, it does not happen here http://bootstrap-confirmation.js.org/

**Comment by ManishJain-JKV** [comment]
Actually in ASP.Net, it is not working with LinkButton in GridView. First time "RowCommand" event is not fired until "Yes" is clicked in confirmation dialog, but after first time it always directly call "RowCommand" without confirmation dialog.

**Comment by mistic100** [comment]
Sorry I can't help you on that.
