### ISSUE TITLE
Not working on dynamically create elements using ajax

### ISSUE THREAD

**Issue by aveshnaik007** [mistic100/Bootstrap-Confirmation#60]
I am trying to assign bootstrap confirmation to a dynamically created button.
when server respond me with an array of object. I place this object using jquery. To delete this object i have added a button. On clicking this button i want bootstrap confirmation to be display, unfortunately the confirmation box doesn't appear. I have added data-toggle="confirmation" attribute to dynamic elements and also enabled confirmation using js.
$('[data-toggle=confirmation]').confirmation({
  rootSelector: '[data-toggle=confirmation]',
  // other options
});
When i add data-toggle="confirmation"  to a static button it works but not from dynamically create elements using ajax

**Comment by mistic100** [comment]
#12

**Comment by mistic100** [comment]
There is nothing new, this behaviour is common to every jQuery plugin AND Bootstrap plugins

```
$('body').confirmation({
rootSelector: 'body',
selector: '[data-toggle=confirmation]',
// other options
});
```

**Comment by aveshnaik007** [comment]
Still not working

**Comment by aveshnaik007** [comment]
still not working


window.getDoctocrPage = function() {
   startSpin();
    $.ajax({
      url : '/clinic/doctor/'+clinic,
      type : 'GET',
      success : function(data) {
         placeBanner(data.banner[0]);
         placeDept(data.department);
         deptments = data.department;

         placeDoctor(data.doctor);
         stopSpin();
      },
      error: function() {
        stopSpin();
        alert('Error');
      }
    });
}

  function placeEachDept(div,tab) {
    div.append(
      '<div class="col-md-6" style="height:auto;"><div class="news-post-box">'+
      '<i onclick="deleteDepartment('+tab.id+',this)" class="fa fa-lg fa-times pull-right"></i>'+
      '&nbsp <i onclick="editDepartment(\''+encodeURI(JSON.stringify(tab))+'\',this)" class="fa fa-lg fa-pencil pull-right" data-toggle="confirmation"></i>'+
      '<div class="inner"><h4>Heading: '+tab.name+'</h4><hr><i class="fa '+tab.icon+' fa-5x"></i>'+
      '<p>Content: '+tab.description+'</p></div></div></div>'
    );
  }

**Comment by mistic100** [comment]
If the delegation is not working, enable the plugin on each item just after adding to the DOM

**Comment by aveshnaik007** [comment]
ya it works but is it optimal solution to it ???
when i created i have to add this code.
when i request for all item that time 
the above code is for one page. there are 20 to 25 of them.

**Comment by mistic100** [comment]
It's equivalent, in both case the plugin is initialized for each item.

**Comment by aveshnaik007** [comment]
so i have to place this code for 25 page which come to 50 times.
50 times i have to place this code

**Comment by aveshnaik007** [comment]
With this there is one problem.
after click delete button. it show confirmation box and delete the div.
I am not click confirmation box yes button but it deletes. it should have been deleted after clicking yes

**Comment by mistic100** [comment]
> 50 times i have to place this code
I think you have to question your code architecture if you have 50 times the same code

>  am not click confirmation box yes button but it deletes. it should have been deleted after clicking yes
It all depends of what you coded, **I can't help you you don't show what you are doing**

**Comment by mistic100** [comment]
Delegation has been proven to work, if it does not on your app, you are not using it correctly or in the right place. Again I can't help you.
