### ISSUE TITLE
Not working on dynamically create elements using ajax

### ISSUE THREAD

**Issue by aveshnaik007** [mistic100/Bootstrap-Confirmation#61]
#60 

Still not working

     window.getDoctocrPage = function() {
    startSpin();
    $.ajax({
    url : '/clinic/doctor/'+clinic,
    type : 'GET',
     success : function(data) {
     placeBanner(data.banner[0]);
     placeDept(data.department);
     deptments = data.department;

     placeDoctor(data.doctor);
     stopSpin();
     },
     error: function() {
      stopSpin();
      alert('Error');
    }
    });
    }

    function placeEachDept(div,tab) {
    div.append(
    '<div class="col-md-6" style="height:auto;"><div class="news-post-box">'+
    '<i onclick="deleteDepartment('+tab.id+',this)" class="fa fa-lg fa-times pull-right"></i>'+
    '&nbsp <i onclick="editDepartment(\''+encodeURI(JSON.stringify(tab))+'\',this)" class="fa fa-lg fa-
       pencil pull-right" data-toggle="confirmation"></i>'+
      '<div class="inner"><h4>Heading: '+tab.name+'</h4><hr><i class="fa '+tab.icon+' fa-5x">
        </i>'+
        '<p>Content: '+tab.description+'</p></div></div></div>'
         );
        }

**Comment by mistic100** [comment]
Do not create another -_- we can discuss on the original

**Comment by aveshnaik007** [comment]
ok
