### ISSUE TITLE
data-on-confirm throwing error

### ISSUE THREAD

**Issue by NickJorens** [mistic100/Bootstrap-Confirmation#62]
`<button class='btn btn-danger' data-toggle="confirmation" data-on-confirm="deleteContact"><i class='fa fa-trash'></i></button>`

results in:

`bootstrap-confirmation.min.js:5 Uncaught TypeError: g.onConfirm is not a function
    at HTMLAnchorElement.<anonymous> (bootstrap-confirmation.min.js:5)
    at HTMLAnchorElement.dispatch (jquery.min.js:3)
    at HTMLAnchorElement.q.handle (jquery.min.js:3)`

**Comment by mistic100** [comment]
If you use like that you must have somewhere in your code: `window.deleteContact = function() {}`

I strongly advise you use events instead.
