### ISSUE TITLE
Replacement for the Standard JavaScript Return Confirm in submit button

### ISSUE THREAD

**Issue by marcoczen** [mistic100/Bootstrap-Confirmation#64]
Hi,

I have a bootstrap form with a submit button as below;

``<button type="submit" class="btn btn-primary" name="button_deluser" > Delete Selected User    
    onclick="return confirm('Proceed with Action?');" </button>
``
  
When the button is clicked - the form is submitted after user confirms. All good BUT  I would like a better looking  confirmation box (Yes - Delete, No - Dont Delete). 
I dont understand how to incorporate bootstrap-confirmation into the button above from the documentation provided.

Any ideas ? Alert - Jquery newbie here.

**Comment by mistic100** [comment]
You only have to do exactly what is written in the doc...

```html
<button type="submit" class="btn btn-primary" name="button_deluser" data-toggle="confirmation" data-title="Proceed with Action?"> Delete Selected User</button>
```

```js
$('[data-toggle=confirmation]').confirmation({
  rootSelector: '[data-toggle=confirmation]'
});
```

**Comment by marcoczen** [comment]
@mistic100  - Will check and revert. Thanks.
