### ISSUE TITLE
Doesnot work 

### ISSUE THREAD

**Issue by askshinde** [mistic100/Bootstrap-Confirmation#65]
$J('[data-toggle=confirmation]').confirmation({
    rootSelector: '[data-toggle=confirmation]',
    popout: false,
    singleton: true,
    html: true
});

This works perfectly fine but as I am using the button in pagination and the issue is that it won't work in any other pagination pages. It wokrs only on the main page. I can catch the event when clicked on paginated pages but it directly opens up the link and confirmation(0 fails without error

**Comment by mistic100** [comment]
#53
