### ISSUE TITLE
NPM: bootstrap-confirmation2 lists no main file and has no index.js, so it can't be directly required.

### ISSUE THREAD

**Issue by delmicio** [mistic100/Bootstrap-Confirmation#67]
I've been struggling with this for two days (first time working with node/npm/webpack)

Now I know I can call it this way:
`require('bootstrap-confirmation2/bootstrap-confirmation.js');`

It would would be nice if you add a main in the package.json
```
{
...
"main": "bootstrap-confirmation.jx",
...
}
```

**Comment by mistic100** [comment]
fixed for both 2.4.1 and 4.0.0
