### ISSUE TITLE
data-btn-cancel/ok-class does not have any effect

### ISSUE THREAD

**Issue by jeffz2012** [mistic100/Bootstrap-Confirmation#74]
as in title
always uses default
using with Metronic

**Comment by mistic100** [comment]
Insufficient info to help.
Create an online demo.
The documentation page works perfectly.

**Comment by jeffz2012** [comment]
Here it goes: http://a4.jpx67.co.uk

Some info, to explain, what I did, what was expected and what came up: 

1. Confirm button
used: data-btn-ok-class="btn-warning"
expected: orange
received: (green) btn-success

2. Cancel button
used: data-btn-cancel-class="btn-info"
expected: blue
received: (red) btn-danger 

HTML 'data' markers used as per: http://bootstrap-confirmation.js.org/#ex-personalization
Other markers like: icon, or label work fine. 

Demo is based on stripped Metronic environment, but full has same results.
I did not test it outside of Metronic ecosys, so maybe it is Metronic, but it is a popular Admin theme, so if it is Metronic, it is good to have it fixed.

Jeff

**Comment by mistic100** [comment]
I digged deep in your code and found in app.min.js

```js
$('[data-toggle=confirmation]').confirmation({
      btnOkClass: 'btn btn-sm btn-success',
      btnCancelClass: 'btn btn-sm btn-danger'
    })
```

Which is taking precedence over data attributes (this is Bootstrap behavior).

It couldn't be Confirmation fault anyway because the defaults values are "primary" and "default"
https://github.com/mistic100/Bootstrap-Confirmation/blob/master/bootstrap-confirmation.js#L47

**Comment by jeffz2012** [comment]
Oops ... 

I should have noticed it myself.
But I am new to Metronic, if it justifies this thread at all (probably not) :)

Thank you for taking your time :)

Jeff.
