### ISSUE TITLE
popover.Constructor.prototype.init is undefined

### ISSUE THREAD

**Issue by Vict0rSch** [mistic100/Bootstrap-Confirmation#77]
Bootstrap Confirmation v2.0
Bootstrap v4.0.0
JQuery 3.2.0

Firefox 52.1.0

Imported as 

```
<script src="path/to/jquery.js"></script>
<script src="path/to/bootstrap.bundle.min.js"></script>
<script src="path/to/bootstrap-confirmation.js"></script>
```

I get this error :

> TypeError: $.fn.popover.Constructor.prototype.init is undefined

**Comment by mistic100** [comment]
It is not compatible with BT 4
 
#51
https://github.com/mistic100/Bootstrap-Confirmation/blob/master/README.md#changes-from-original-one
