### ISSUE TITLE
Broken CDN

### ISSUE THREAD

**Issue by ppazos** [mistic100/Bootstrap-Confirmation#78]
https://cdn.jsdelivr.net/npm/bootstrap-confirmation2/dist/js/bootstrap-confirmation.min.js

file not found

**Comment by ppazos** [comment]
@mistic100 why is this closed without comment?

**Comment by ppazos** [comment]
BTW broken link to CDN is on this page http://bootstrap-confirmation.js.org/

**Comment by mistic100** [comment]
It's closed from a commit !

**Comment by ppazos** [comment]
+1 :)
