### ISSUE TITLE
wrong release description

### ISSUE THREAD

**Issue by ppazos** [mistic100/Bootstrap-Confirmation#79]
Compatible with Bootstrap 4 only (for Bootstrap 4, use version 2.x.x).

Should it be this?
 (for Bootstrap 3, use version 2.x.x).

**Comment by mistic100** [comment]
done

**Comment by ppazos** [comment]
thanks, BTW aswesome plugin, will start using it for my project https://github.com/ppazos/cabolabs-ehrserver
