### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by scorpiozj** [mistic100/Bootstrap-Confirmation#80]
I use confirmation like: `script(type='text/javascript', src='https://cdn.jsdelivr.net/npm/bootstrap-confirmation2/dist/bootstrap-confirmation.min.js')`

The jquery 3.2.1 and bootstrap 3.3.7 are added before it. When run the page, it shows:
 
> Uncaught SyntaxError: Unexpected identifier

I do use bootstrap 3.x, but it shows bootstrap 4 in console.  
How can I fix it? 

<img width="1420" alt="2018-04-19 3 35 26" src="https://user-images.githubusercontent.com/644156/38977590-60cec73a-43e7-11e8-86e0-9aa8a8b63a55.png">

<img width="785" alt="2018-04-19 3 35 12" src="https://user-images.githubusercontent.com/644156/38977611-71c76006-43e7-11e8-93fa-076b0bd2e4dd.png">

**Comment by mistic100** [comment]
This is clearly explained in the readme ! https://github.com/mistic100/Bootstrap-Confirmation#installation

Use version 2 https://cdn.jsdelivr.net/npm/bootstrap-confirmation2@2.4.1/bootstrap-confirmation.min.js

**Comment by scorpiozj** [comment]
thanks.  
not familiar with web development.
was strange how to use npm...
