### ISSUE TITLE
Webpack / Webpack-encore

### ISSUE THREAD

**Issue by oxodao** [mistic100/Bootstrap-Confirmation#81]
Hi,

I can't get this to work with webpack. I made sure to have jQuery and Popper as autoProvideVariables, and imported bootstrap at the top of my js file.
Then calling it result in an error
```
require('bootstrap-confirmation/bootstrap-confirmation');
$(document).ready(function() {
    $('[data-toggle=confirmation]').confirmation({
        rootSelector: '[data-toggle=confirmation]',
        // other options
    });
});
```

> TypeError: this.init is not a function (bootstrap-confirmation.js:38)

**Comment by mistic100** [comment]
The only place where I could find "this.init" on line 38 is on the original project of jibe914 https://github.com/jibe914/Bootstrap-Confirmation

So you installed the wrong package, this one is called `bootstrap-confirmation2`, please carefully read what is written on the "Download" popup here http://bootstrap-confirmation.js.org/ to know which version you need.

**Comment by oxodao** [comment]
Indeed I used the wrong package, sorry for this.

But now it looks like it works even less, I get this error:
> TypeError: $(...).confirmation is not a function

No matter which file I require, even if I only require the package name...
I am using Bootstrap 4

**Comment by mistic100** [comment]
Unfortunately I don't know how I can help you. Webpack is so much about configuration and edge behaviours (I worked for about three weeks straight setuping the new build tools for my work) I just cannot point where your problem could be.
