### ISSUE TITLE
v2.4.1 - mobile?

### ISSUE THREAD

**Issue by phackwer** [mistic100/Bootstrap-Confirmation#82]
Why the dialog doesn't show up in chrome mobile? It goes just like a link, without making questions.

All I did was, using Chrome, switch the view from desktop to mobile using Developer's tool, but it also didn't work from my cellphone. Funny fact: if I switch from mobile back to desktop, it works again. So, it's definitely something related to mobile compatibility (or latest Chrome being a bitch, as usual... had a funny bug lately with rotate transformation, just because the parent div had a background-color, hahaha).

**Comment by mistic100** [comment]
Close for #84
