### ISSUE TITLE
How to delete the popup trigger listener?

### ISSUE THREAD

**Issue by zhaoyi0113** [mistic100/Bootstrap-Confirmation#83]
I am using javascript to enable confirmation as below:

> $ (className).confirmation (...)

when I click the dom with the given `className` will trigger the confirmation dialog. I wonder how I can remove this click event through javascript?

**Comment by mistic100** [comment]
Use `trigger: 'manual'`as described in the Popover documentation https://getbootstrap.com/docs/4.1/components/popovers/#options

(my documentation explicitly states that all Popover options are available).

**Comment by mistic100** [comment]
If you use version 4 you can use `trigger: 'manual'` as described in [Popover documentation](http://getbootstrap.com/docs/4.1/components/popovers/#options) (Confirmation documentation saying the "trigger" cannot be overridden is wrong).

If you use version 3 it's not possible.
