### ISSUE TITLE
Does not work on mobile when inside RubaXa/Sortable

### ISSUE THREAD

**Issue by bdteo** [mistic100/Bootstrap-Confirmation#84]
Using `touchstart` when available instead of `click` solves the problem.

**Comment by mistic100** [comment]
> Using touchstart when available instead of click solves the problem.

Where ?

**Comment by bdteo** [comment]
... on the .confirmation() element itself ...

Firstly I thought that there was a problem with touch events on mobile devices. Sorry for the false alarm.

The actual problem is that (in Chrome at least) when touch events are bound to an element neither its children nor the element itself receive click events (when touch events are supported).

So .... It seems that Bootstrap Confirmation will not be compatible at all with any other library that binds touch events to a `confirmation` or any of its parent elements.

Adding touch events support will make Bootstrap Confirmation compatible with many more libraries.

**Comment by mistic100** [comment]
Can you make a repro ?
My test does work on Chrome Android https://jsfiddle.net/nsuayj9v/6/

**Comment by mistic100** [comment]
By the way, this behaviour is handled by Bootstrap itself, Confirmation is totally based on Popover
If Popovers do not work, I will not make a special case for Confirmation.

**Comment by bdteo** [comment]
Test it in the Chrome Mobile Emulator.

https://jsfiddle.net/w9r70s1z/51/

It only breaks in Chrome  for Android, Android Browser and iOS.

I could not break it in the Mozilla Firefox Mobile Emulator.

**Comment by mistic100** [comment]
As I suspected the problem is in Bootstrap itself, switching to Popover produces the same behaviour.
I won't try to fix it just for Confirmation, sorry. Your "fix" seems simple but by experience this kind of code has 99% chance to break something else without a good expertise (which Bootstrap team has but I have not).

I also wonder why you "preventDefault", because this is the root of the problem.

**Comment by bdteo** [comment]
As I said in the beginning I was using bootstrap-confirmation along with RubaXa/Sortable.

As far as I remember RubaXa/Sortable was attaching event handler that calls `preventDefault()`.
This is why I am including it in the example.

There is a possibility that another plugin does the same and it will break Bootstrap-Confirmation.

Re-propagating `touchstart` as a `click` event is the way I solved it in my codebase.
I undestand that this approach is not robust enough to be used in a library. It is just for the example.

I find browsers' handling of `click` and `touch` events together to be inconsistent.

It seems that preventDefault() on Chrome prevents the implicit `touch` to `click` re-propagation.
It seems quite reasonable behaviour.

However, as you can see the lack of good touch event definitions results in undefined behaviour. I am expecting that there are other scenarios (regarding click/touch events) that will break the popover, too.
