### ISSUE TITLE
How to import in SCSS file?

### ISSUE THREAD

**Issue by Quix0r** [mistic100/Bootstrap-Confirmation#85]
I have done `npm install bootstrap-confirmation2`. I then usually do `npm run-script prod` to compile/bundle the CSS/JS files.

I now have difficulties to somehow `@import` it in my main `app.scss` file. Sadly the documentation doesn't say anything about this.

The mentioned `prod` script does the following: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`

Content of `app.scss`:
````
// Variables
@import "variables";

// Bootstrap
@import '~bootstrap/scss/bootstrap';

// Bootstrap-confirmation 2
@import '~bootstrap-confirmation2/src/confirmation';
````
The one for bootstrap works because it has a "main" scss file, but not confirmation2. Any help is much appreciated.

**Comment by mistic100** [comment]
There is no CSS for Confirmation...
https://github.com/mistic100/Bootstrap-Confirmation/tree/master/dist

**Comment by Quix0r** [comment]
Ah, I confused including CSS and JS. Sorry for the noise!
