### ISSUE TITLE
Prevent default

### ISSUE THREAD

**Issue by margaale** [mistic100/Bootstrap-Confirmation#87]
Hi, i'm using the confirmation on an submit button (actually is an asp:button). It seems that after clicking ok there is no way on preventing postback, is this right? I get no event parameter on the onConfirm callback.

**Comment by mistic100** [comment]
So you want your submit to not actually submit ?

I think the best way will be to set your button's type as "button", this way it will not be a submit button, and you can to whatever you want in the confirmation callback/event.

**Comment by margaale** [comment]
Yep, thats what i did in the midtime. I have to run some form validations
before submitting the form, that's why i was asking this.

**Comment by mistic100** [comment]
You just need to chain the event handlers

```js
$('#button').confirmation()
  .on('click', function(e) {
    if (false) {
      e.preventDefault();
    }
  });
```

your own event handler will only be called after the confirmation is accepted
