### ISSUE TITLE
AJAX + multiple DIFFERENT confirmation buttons/titles for different selectors

### ISSUE THREAD

**Issue by tomasztopa** [mistic100/Bootstrap-Confirmation#89]
I am trying to get different confirmation titles and custom buttons on multiple different links that can be loaded via ajax. The callback functions would heavily rely on data passed by the items provided in copyAttributes.

.buttons-labeled-a would have a different set of options than .buttons-labeled-b. And .buttons-labeled-c would be added next week, .buttons-labeled-d next month etc. My Client is very good at new ideas :)

I assumed that something like this would work:

```
jQuery('body').confirmation({
    rootSelector: 'body',
    copyAttributes: 'data-current-status data-type',
    selector:   '.buttons-labeled-a',
    title: 'What do you think about Buttons Labeled A?',
    html: true,
    buttons: [
                {
                    label: 'I have no idea',
                    class: 'btn btn-cancel',
                    cancel: true
                },
                
                {
                    label: 'I hate them',
                    class: 'btn btn-default',
                    onClick: function(){
                        // something to hate
                    }
                },

                {
                    label: 'I love them',
                    class: 'btn btn-primary',
                    onClick: function(){
                        // something to love
                    }
                }
    ]
});

jQuery('body').confirmation({
    rootSelector: 'body',
    copyAttributes: 'data-current-status data-type',
    selector:   '.buttons-labeled-b',
    title: 'What song do you want to sing?',
    html: true,
    buttons: [
                {
                    label: 'I do not want to sing',
                    class: 'btn btn-cancel',
                    cancel: true
                },
                
                {
                    label: 'Song #1',
                    class: 'btn btn-default',
                    onClick: function(){
                        // Never gonna give you up!
                    }
                },

                {
                    label: 'Song #2',
                    class: 'btn btn-primary',
                    onClick: function(){
                        // Never gonna let you down 
                    }
                }
    ]
});

```

but only the first set is created, all .buttons-labeled-b links are ignored. Tried different variations based on different selectors / rootSelectors, but could not get anything to work.

As a temp hotfix I use a single init using with a dozen of selector options and a hundred of buttons, a small tweak adding different classes to the popover container depending on the link's class and a lot of CSS lines to hide the unnecessary buttons:

```
jQuery('body').confirmation({
    rootSelector: 'body',
    copyAttributes: 'data-current-status data-type',
    selector: '.item-a, .item-b, .item-c, .... , .item-z',
    buttons: [
        //a gazillion of buttons
    ]
})

```

But it is not usable nad maintainable in the long term.

Any suggestions, solutions...?

Using Bootstrap 4.1 and Bootstrap Confirmation 4.0

**Comment by mistic100** [comment]
I would say it's a bug (or a missing feature), the second register being ignored because the plugin is already registered on the body. The fact is the register itself is handled by Bootstrap Popover, **if** you try to register multiple delegated Popovers and it does not work either, I cannot do anything, I take the decision to never try to fix Bootstrap core behaviour.

A much simpler solution for you is to not use delegation and init the Confirmations when you know your DOM is updated. It does not matter you re-select all buttons (even already initialized ones).

**Comment by tomasztopa** [comment]
Thank you for a prompt reply.

So a really quick test with something like:

```
function addConfirmations(){
    jQuery('.buttons-labeled-a').confirmation({
        copyAttributes: 'data-current-status data-type',
        title: 'What do you think about Buttons Labeled A?',
        html: true,
        buttons: [
                    {
                        label: 'I have no idea',
                        class: 'btn btn-cancel',
                        cancel: true
                    },
                    
                    {
                        label: 'I hate them',
                        class: 'btn btn-default',
                        onClick: function(){
                            // something to hate
                        }
                    },

                    {
                        label: 'I love them',
                        class: 'btn btn-primary',
                        onClick: function(){
                            // something to love
                        }
                    }
        ]
    });

    jQuery('.buttons-labeled-b').confirmation({
        copyAttributes: 'data-current-status data-type',
        title: 'What song do you want to sing?',
        html: true,
        buttons: [
                    {
                        label: 'I do not want to sing',
                        class: 'btn btn-cancel',
                        cancel: true
                    },
                    
                    {
                        label: 'Song #1',
                        class: 'btn btn-default',
                        onClick: function(){
                            // Never gonna give you up!
                        }
                    },

                    {
                        label: 'Song #2',
                        class: 'btn btn-primary',
                        onClick: function(){
                            // Never gonna let you down 
                        }
                    }
        ]
    });
}
```

and firing addConfirmations() on jQuery(document).ready(function(){ ... }) and all the jQuery.get('...').done(function(data){ ... }) with new links/items added by append() seems to do the trick. 

I'll do some more testing in the morning, but for now the only downside I can see is that the singleton option will work only in the specific group of links ('.buttons-labeled-a' / '.buttons-labeled-b' etc). But it is still a good tradeoff considering all the cons of my previous workaround.

Thanks for pointing in the right direction :)

**Comment by seyfer** [comment]
@tomasztopa how you solved it in the end?
because since jQuery3 you need to use `rootSelector` to be able to use `singleton` option. And then you must provide `selector` option because if not registered on `body` it does not work. And we return back to your first post - only one set of options is registered...

**Comment by seyfer** [comment]
@tomasztopa, @mistic100  is there a way to fix singleton between different confirmation configs?

I have tried this approach:
```
$element.on('show.bs.confirmation', function() {
        $('.popover.confirmation').hide();
    });
```

it hides all other popovers. but has a bug
when I click first on the first group - it shows popover from 1 click
then when I click on the second group - I need to click 2 times to make it be shown again. so switch between groups requires 2 clicks.

**Comment by tomasztopa** [comment]
@seyfer I ditched the singleton in the end as it was not that crucial in my project. I ended up with addConfirmations() function attaching all the different variants to all sort of different selectors and firing it up every AJAX call that could change the selectors.

I can't remember now exactly how did I try to simulate the singleton option, but I would try using the confirmation('hide') action to actually close the previous popovers rather than just hiding them with .hide():

```
$element.on('show.bs.confirmation', function(){
	$('all_other_elements_with_possible_confirmations').each(function(){
		if([check if this is not the element last clicked]){
			// ^^ I can't remember what values are actually returned, sorry :)
			$(this).confirmation('hide');
		}
	});
});
```
