### ISSUE TITLE
Not firing on dynamic content

### ISSUE THREAD

**Issue by BinarySpike** [mistic100/Bootstrap-Confirmation#91]
In bootstrap 3.3, I have a list of items that gets loaded from xhr long after I've initialized the confirmation.  Unfortunately, the confirmation is not fired on the click event for those buttons.  I researched how you're supposed to do popovers and got this code working:

```
$('body').confirmation({
    rootSelector: '[data-toggle=confirmation]',
    selector: '[data-toggle=confirmation]',
});
```

The "selector" option is not documented by bootstrap-confirmation, but it is bootstrap popover (v3.3).

Is this a good way of handling dynamically loaded buttons—if so, does it need to be documented?

**Comment by mistic100** [comment]
Yes it is the best way.

No it won't be explicitly in the documentation because the options array starts by :
> All options from Bootstrap Popover can be used, see Bootstrap 4 Popover and Bootstrap 3 Popover.

Have a nice day
