### ISSUE TITLE
No way to make the confirmation conditional?

### ISSUE THREAD

**Issue by vsajip** [mistic100/Bootstrap-Confirmation#98]
There are situations where you want a confirmation to be enabled or disabled depending on context. For example, if a user would lose data by clicking a button such as "logout", you want to get confirmation from the user. However, if no data would be lost, then you shouldn't need confirmation.

This could be done by having an additional callback configured which, if it returned true, would automatically call the confirm callback, else go ahead and display the confirmation popover.

**Comment by mistic100** [comment]
Please try https://github.com/mistic100/Bootstrap-Confirmation/issues/90

Sent from MailDroid

-----Original Message-----

**Comment by vsajip** [comment]
OK, thanks for the pointer. I think there might be yet another way to do this - set the trigger to something other than 'click' (say, 'confirm') and then the 'click' handler for the button could check the condition and then trigger 'confirm' if needed.

**Comment by mistic100** [comment]
Yes this is the second solution gave by eight19
